"""Make name and user_id combination unique

Revision ID: 7ace9eb9ce49
Revises: 30cd19f4b507
Create Date: 2025-02-24 14:16:07.014765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ace9eb9ce49'
down_revision = '30cd19f4b507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_name_user_id', ['name', 'user_id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_name_user_id', ['name', 'user_id'])

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_name_user_id', ['name', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_user_id', type_='unique')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_user_id', type_='unique')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_user_id', type_='unique')

    # ### end Alembic commands ###
